### ISSUE TITLE
🎯 What can I work on ? (Open Food Facts C# SDK)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-csharp#3]
### 🎯 What can I work on ? (Open Food Facts C# SDK)

- Listing existing features of the SDK
- Implementing missing features
- READ/WRITE
- Main API, Prices, Search-a-licious, …
- Image upload, field editing, Robotoff (ML), …

### Tasks
- [ ] Implement the Open Prices APIs
- [ ] Implement the Folksonomy Engine APIs
- [ ] Implement the Robotoff APIs
- [ ] Implement the Knowledge Panels for Facets APIs
- [ ] Implement the Search-A-Licious APIs
- [ ] Check that the image upload API is implemented
- [ ] Check that the field editing API is implemented
- [ ] Implement Open (Pet Food, Beauty, Products Facts) support
